use serde::{Deserialize, Serialize};

#[cfg(test)]
mod tests;

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(rename_all = "lowercase")]
pub enum Language {
    #[default]
    Auto,
    EN,
    SQ,
    AR,
    AZ,
    EU,
    BN,
    BG,
    CA,
    #[serde(rename = "zh-Hans")]
    ZhHans,
    #[serde(rename = "zh-Hant")]
    ZhHant,
    CS,
    DA,
    NL,
    EO,
    ET,
    FI,
    FR,
    GL,
    DE,
    EL,
    HE,
    HI,
    HU,
    ID,
    GA,
    IT,
    JA,
    KO,
    KY,
    LV,
    LT,
    MS,
    NB,
    FA,
    PL,
    PT,
    #[serde(rename = "pt-BR")]
    PtBR,
    RO,
    RU,
    SR,
    SK,
    SL,
    ES,
    SW,
    SV,
    TL,
    TH,
    TR,
    UK,
    UR,
    VI,
}

impl Language {
    pub const ALL: &'static [Language] = &[
        Language::Auto,
        Language::EN,
        Language::SQ,
        Language::AR,
        Language::AZ,
        Language::EU,
        Language::BN,
        Language::BG,
        Language::CA,
        Language::ZhHans,
        Language::ZhHant,
        Language::CS,
        Language::DA,
        Language::NL,
        Language::EO,
        Language::ET,
        Language::FI,
        Language::FR,
        Language::GL,
        Language::DE,
        Language::EL,
        Language::HE,
        Language::HI,
        Language::HU,
        Language::ID,
        Language::GA,
        Language::IT,
        Language::JA,
        Language::KO,
        Language::KY,
        Language::LV,
        Language::LT,
        Language::MS,
        Language::NB,
        Language::FA,
        Language::PL,
        Language::PT,
        Language::PtBR,
        Language::RO,
        Language::RU,
        Language::SR,
        Language::SK,
        Language::SL,
        Language::ES,
        Language::SW,
        Language::SV,
        Language::TL,
        Language::TH,
        Language::TR,
        Language::UK,
        Language::UR,
        Language::VI,
    ];

    pub fn code(&self) -> &'static str {
        match self {
            Language::Auto => "auto",
            Language::EN => "en",
            Language::SQ => "sq",
            Language::AR => "ar",
            Language::AZ => "az",
            Language::EU => "eu",
            Language::BN => "bn",
            Language::BG => "bg",
            Language::CA => "ca",
            Language::ZhHans => "zh-hans",
            Language::ZhHant => "zh-hant",
            Language::CS => "cs",
            Language::DA => "da",
            Language::NL => "nl",
            Language::EO => "eo",
            Language::ET => "et",
            Language::FI => "fi",
            Language::FR => "fr",
            Language::GL => "gl",
            Language::DE => "de",
            Language::EL => "el",
            Language::HE => "he",
            Language::HI => "hi",
            Language::HU => "hu",
            Language::ID => "id",
            Language::GA => "ga",
            Language::IT => "it",
            Language::JA => "ja",
            Language::KO => "ko",
            Language::KY => "ky",
            Language::LV => "lv",
            Language::LT => "lt",
            Language::MS => "ms",
            Language::NB => "nb",
            Language::FA => "fa",
            Language::PL => "pl",
            Language::PT => "pt",
            Language::PtBR => "pt-br",
            Language::RO => "ro",
            Language::RU => "ru",
            Language::SR => "sr",
            Language::SK => "sk",
            Language::SL => "sl",
            Language::ES => "es",
            Language::SW => "sw",
            Language::SV => "sv",
            Language::TL => "tl",
            Language::TH => "th",
            Language::TR => "tr",
            Language::UK => "uk",
            Language::UR => "ur",
            Language::VI => "vi",
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Language::Auto => "Auto",
            Language::EN => "English",
            Language::SQ => "Albanian",
            Language::AR => "Arabic",
            Language::AZ => "Azerbaijani",
            Language::EU => "Basque",
            Language::BN => "Bengali",
            Language::BG => "Bulgarian",
            Language::CA => "Catalan",
            Language::ZhHans => "Chinese",
            Language::ZhHant => "Chinese (traditional)",
            Language::CS => "Czech",
            Language::DA => "Danish",
            Language::NL => "Dutch",
            Language::EO => "Esperanto",
            Language::ET => "Estonian",
            Language::FI => "Finnish",
            Language::FR => "French",
            Language::GL => "Galician",
            Language::DE => "German",
            Language::EL => "Greek",
            Language::HE => "Hebrew",
            Language::HI => "Hindi",
            Language::HU => "Hungarian",
            Language::ID => "Indonesian",
            Language::GA => "Irish",
            Language::IT => "Italian",
            Language::JA => "Japanese",
            Language::KO => "Korean",
            Language::KY => "Kyrgyz",
            Language::LV => "Latvian",
            Language::LT => "Lithuanian",
            Language::MS => "Malay",
            Language::NB => "Norwegian",
            Language::FA => "Persian",
            Language::PL => "Polish",
            Language::PT => "Portuguese",
            Language::PtBR => "Portuguese (Brazil)",
            Language::RO => "Romanian",
            Language::RU => "Russian",
            Language::SR => "Serbian",
            Language::SK => "Slovak",
            Language::SL => "Slovenian",
            Language::ES => "Spanish",
            Language::SW => "Swahili",
            Language::SV => "Swedish",
            Language::TL => "Tagalog",
            Language::TH => "Thai",
            Language::TR => "Turkish",
            Language::UK => "Ukrainian",
            Language::UR => "Urdu",
            Language::VI => "Vietnamese",
        }
    }
}
