use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Language {
    #[default]
    Auto,
    EN,
    SQ,
    AR,
    AZ,
    EU,
    BN,
    BG,
    CA,
    #[serde(rename = "zh-Hans")]
    ZhHans,
    #[serde(rename = "zh-Hant")]
    ZhHant,
    CS,
    DA,
    NL,
    EO,
    ET,
    FI,
    FR,
    GL,
    DE,
    EL,
    HE,
    HI,
    HU,
    ID,
    GA,
    IT,
    JA,
    KO,
    KY,
    LV,
    LT,
    MS,
    NB,
    FA,
    PL,
    PT,
    #[serde(rename = "pt-BR")]
    PtBR,
    RO,
    RU,
    SR,
    SK,
    SL,
    ES,
    SW,
    SV,
    TL,
    TH,
    TR,
    UK,
    UR,
    VI,
}

impl Language {
    pub const ALL: &'static [Language] = &[
        Language::Auto,
        Language::EN,
        Language::SQ,
        Language::AR,
        Language::AZ,
        Language::EU,
        Language::BN,
        Language::BG,
        Language::CA,
        Language::ZhHans,
        Language::ZhHant,
        Language::CS,
        Language::DA,
        Language::NL,
        Language::EO,
        Language::ET,
        Language::FI,
        Language::FR,
        Language::GL,
        Language::DE,
        Language::EL,
        Language::HE,
        Language::HI,
        Language::HU,
        Language::ID,
        Language::GA,
        Language::IT,
        Language::JA,
        Language::KO,
        Language::KY,
        Language::LV,
        Language::LT,
        Language::MS,
        Language::NB,
        Language::FA,
        Language::PL,
        Language::PT,
        Language::PtBR,
        Language::RO,
        Language::RU,
        Language::SR,
        Language::SK,
        Language::SL,
        Language::ES,
        Language::SW,
        Language::SV,
        Language::TL,
        Language::TH,
        Language::TR,
        Language::UK,
        Language::UR,
        Language::VI,
    ];

    pub fn as_str(&self) -> &'static str {
        match self {
            Language::Auto => "Auto",
            Language::EN => "English",
            Language::SQ => "Albanian",
            Language::AR => "Arabic",
            Language::AZ => "Azerbaijani",
            Language::EU => "Basque",
            Language::BN => "Bengali",
            Language::BG => "Bulgarian",
            Language::CA => "Catalan",
            Language::ZhHans => "Chinese",
            Language::ZhHant => "Chinese (traditional)",
            Language::CS => "Czech",
            Language::DA => "Danish",
            Language::NL => "Dutch",
            Language::EO => "Esperanto",
            Language::ET => "Estonian",
            Language::FI => "Finnish",
            Language::FR => "French",
            Language::GL => "Galician",
            Language::DE => "German",
            Language::EL => "Greek",
            Language::HE => "Hebrew",
            Language::HI => "Hindi",
            Language::HU => "Hungarian",
            Language::ID => "Indonesian",
            Language::GA => "Irish",
            Language::IT => "Italian",
            Language::JA => "Japanese",
            Language::KO => "Korean",
            Language::KY => "Kyrgyz",
            Language::LV => "Latvian",
            Language::LT => "Lithuanian",
            Language::MS => "Malay",
            Language::NB => "Norwegian",
            Language::FA => "Persian",
            Language::PL => "Polish",
            Language::PT => "Portuguese",
            Language::PtBR => "Portuguese (Brazil)",
            Language::RO => "Romanian",
            Language::RU => "Russian",
            Language::SR => "Serbian",
            Language::SK => "Slovak",
            Language::SL => "Slovenian",
            Language::ES => "Spanish",
            Language::SW => "Swahili",
            Language::SV => "Swedish",
            Language::TL => "Tagalog",
            Language::TH => "Thai",
            Language::TR => "Turkish",
            Language::UK => "Ukrainian",
            Language::UR => "Urdu",
            Language::VI => "Vietnamese",
        }
    }
}
